server:
  port: 8081
spring:
  application:
    name: payment-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/payments}
    username: ${DB_USERNAME:bank}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      acks: all
      properties:
        enable.idempotence: true
        delivery.timeout.ms: 15000
        request.timeout.ms: 5000
bank:
  outbox:
    batch-size: 20
    max-attempts: 10
  reconciliation:
    delay-ms: 5000
    max-attempts: 8
  recovery:
    delay-ms: 60000
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
logging:
  pattern:
    level: "%5p [correlationId:%X{correlationId:-none}]"
